spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
#    url: jdbc:postgresql://localhost:5432/memberTest
#    username: root
#    password: 1234
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

elasticsearch:
  host: ${ELASTICSEARCH_HOST:localhost}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:123456}


